name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
        
      - name: Create Release
        run: |
          mkdir -p builds
          cp build/outputs/apk/debug/filmizlesene-plugin-debug.apk builds/plugin.cs3
          echo '{"name":"Filmizlesene","description":"Filmizlesene.de için Cloudstream eklentisi","version":1,"plugins":[{"status":1,"version":1,"name":"Filmizlesene","description":"Filmizlesene.de için Cloudstream eklentisi","authors":["Cloudstream Kullanıcısı"],"language":"tr","url":"https://raw.githubusercontent.com/${{ github.repository }}/builds/plugin.cs3"}]}' > builds/repo.json
          
      - name: Push to builds branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan builds
          git rm -rf .
          cp -r builds/* .
          git add .
          git commit -m "Build ${{ github.sha }}"
          git push -f origin builds
